name: cinema_ticketing
description: A cinema ticketing system with red and black theme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.4.0

  qr_flutter: ^4.1.0
  
  mobile_scanner: ^7.0.1
  
  # UI
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # Local Database
  sqflite: ^2.3.0
  path: ^1.9.0

  # REST API
  http: ^1.1.0

  # Device Features
  image_picker: ^1.0.5

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2

  # URL Launcher for YouTube
  url_launcher: ^6.2.1
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/